# Generated by Django 4.1.6 on 2023-02-06 09:01

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', django_fsm.FSMField(default='unverified', max_length=50, protected=True)),
            ],
        ),
    ]
