# Generated by Django 4.1.6 on 2023-02-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
