# Generated by Django 4.1.6 on 2023-02-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsmtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition_Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsmtest.post')),
            ],
        ),
    ]
